<?php
return [
    // ── Navbar ──────────────────────────────────────────
    'share_animation' => 'Animáció megosztása',
    'hide_timeline' => 'Idővonal elrejtése',
    'shrink_timeline' => 'Idővonal kicsinyítése',
    'hide_code' => 'Kód elrejtése',
    'go_to_editor' => 'Szerkesztő',

    // ── Drag box / code panel ───────────────────────────
    'your_code' => 'Kódod',
    'placeholder_code' => 'Írd ide a kódot',
    'placeholder_vars' => 'További változók (opcionális)',
    'placeholder_call' => 'Paraméterek megadása',
    'execute' => 'Futtatás',

    // ── Share modal ─────────────────────────────────────
    'share_modal_title' => 'Animáció megosztása',
    'your_name' => 'Neved',
    'name_placeholder' => 'Add meg a neved',
    'anim_title' => 'Animáció címe',
    'title_placeholder' => 'Adj címet az animációnak',
    'cancel' => 'Mégse',
    'continue' => 'Tovább',

    // ── Share status popup ───────────────────────────────
    'shared_ok' => 'Az animáció sikeresen megosztva.',
    'share_err_fields' => 'Add meg a neved és az animáció címét.',
    'share_err_no_data' => 'Nincs mentett animáció. Először futtass egyet.',
    'share_err_folder' => 'Nem sikerült létrehozni a megosztási mappát.',
    'share_label_title' => 'Cím:',
    'share_label_by' => 'Készítette:',
    'copy_link' => 'Link másolása',
    'copied' => 'Kimásolva',
    'copy_failed' => 'Másolás sikertelen',
    'close' => 'Bezár',

    // ── Share meta panel (shared view) ──────────────────
    'meta_author' => 'Szerző',
    'meta_title' => 'Cím',
    'meta_created' => 'Létrehozva',

    // ── Captcha / execute feedback ───────────────────────
    'captcha_fail' => 'A futtatáshoz előbb igazold, hogy nem vagy robot.',

    // ── Algorithms dropdown ──────────────────────────────
    'algo_custom' => 'Saját kód',
    'algo_fibonacci' => 'Fibonacci',
    'algo_factorial' => 'Faktoriális',
    'algo_knapsack' => '0–1 hátizsák',
    'algo_coin_change' => 'Pénzváltás',
    'algo_sum_digits' => 'Számjegyek összege',
    'algo_binary_search' => 'Bináris keresés',
    'algo_power' => 'Hatványozás',
    'algo_palindrome' => 'Palindróm',
    "back_button" => "⬅ Vissza a vizualizátorhoz",

    "what_is_recursion" => "Mi a rekurzió",
    "recursion_definition" => "A rekurzió egy olyan technika, amikor egy függvény saját magát hívja meg.",
    "recursion_simple_think" => "Gondolj rá így:",
    "recursion_simple_formula" => "\"Megold n → megold n-1 → n-2 → ... amíg el nem érjük az egyszerű esetet\"",

    "how_recursion_works_title" => "Hogyan működik a rekurzió",
    "how_recursion_works_1" => "Minden alkalommal, amikor egy függvény meghívja önmagát, új szint kerül a verembe.",
    "call_stack_intro" => "A hívási verem tárolja:",
    "call_stack_items_intro" => "Ez tartalmazza:",
    "call_stack_item_1" => "függvényparamétereket",
    "call_stack_item_2" => "lokális változókat",
    "call_stack_item_3" => "visszatérési címet",
    "stack_unwind" => "Amikor elérjük a bázisesetet, a verem visszabomlik.",

    "fibonacci_title" => "Fibonacci — miért lassú a rekurzió",
    "fibonacci_code_intro" => "Kód példa:",
    "fibonacci_explanation" => "Az algoritmus többször újraszámolja ugyanazokat az értékeket.",
    "fibonacci_example" => "Példa: fibonacci(5) többször kiszámolja a fibonacci(3)-at.",

    "digits_title" => "Számjegyek összege",
    "digits_intro" => "A számjegyek összegét rekurzívan számoljuk ki.",
    "digits_example" => "1234 → 1 + 2 + 3 + 4 = 10",

    "thinking_process" => "Gondolkodási folyamat",
    "digits_breakdown_intro" => "A számot utolsó számjegyre és maradékra bontjuk.",
    "digits_formula" => "sum(n) = utolsó_számjegy + sum(maradék)",

    "cpp_solution" => "C++ megoldás",
    "step_by_step" => "Lépésről lépésre",

    "step1" => "sumDigits(1234)",
    "step2" => "= 4 + sumDigits(123)",
    "step3" => "= 4 + 3 + sumDigits(12)",
    "step4" => "= 4 + 3 + 2 + sumDigits(1)",
    "step5" => "= 4 + 3 + 2 + 1 + sumDigits(0)",
    "step6" => "= 4 + 3 + 2 + 1 + 0",
    "result" => "= 10",

    "why_it_works" => "Miért működik",
    "why_it_works_text" => "A probléma lépésről lépésre egyszerűsödik, amíg el nem érjük a bázisesetet.",

    "important_note" => "Fontos részlet",
    "integer_division_note" => "Egészosztás: 123 / 10 = 12",
    "filters"=> "Vizualizációs",
    "ai_sidebar_subtitle" => "Tanulj meg rekurzióról saját kódoddal.",
    "ai_response_label" => "Válasz",
    "send"=> "Küldés",
    "copy"=> "Másolás",
    "clear"=> "Törlés",
    "your_name"=> "Neved",
    "anim_title"=> "Animáció címe",
    "learn_recursion"=> "Rekurzió tanulása",
    "execute"=> "Végrehajtás",
    "ai_sidebar_title"=> "AI Asszisztens",
    "legend_param"=> "Függvény paraméter",
    "legend_connection"=> "Kapcsolat vonal",
    "legend_direction"=> "Irány",
    "legend_value"=> "Érték",
    "legend_final_number"=> "Végső szám",
    "nodes"=> "Csomópontok",
    "levels"=> "Szintek",
    "output"=> "Program kimenet",
    "back_button" => "Vissza",
    "page_title" => "Recursio • Rekurzív Algoritmusok Mesterfokon",
    "hero_title" => "Sajatítsd el a<br><span class=\"gradient-text\">Rekurzív Gondolkodást</span>",
    "hero_subtitle" => "Tanuld meg pontosan, hogyan működnek a rekurzív függvények, miért olyan erősek, és hogyan írd meg őket magabiztosan.",

    "core_concept" => "ALAPFOGALOM",
    "how_to_think_recursively" => "Hogyan Gondolkodj Rekurzívan",
    "how_to_think_recursively_desc" => "Minden rekurzív függvény ugyanazt a 3 összetevős receptet követi. Sajátítsd el ezeket, és szinte bármilyen rekurzív problémát meg tudsz oldani.",

    "base_case_title" => "1. Alapeset",
    "base_case_desc" => "A leállási feltétel. Nélküle a rekurzió soha nem ér véget.",
    "base_case_explanation" => "Ez a probléma legegyszerűbb változata, amelyet közvetlenül meg lehet oldani.",

    "recursive_case_title" => "2. Rekurzív eset",
    "recursive_case_desc" => "Az a rész, ahol a függvény önmagát hívja meg egy kisebb problémával.",
    "recursive_case_explanation" => "Ez a nagy problémát kisebb, azonos problémára bontja.",

    "progress_title" => "3. Haladás",
    "progress_desc" => "Minden hívásnál közelebb kell kerülni az alapesethez.",
    "progress_patterns" => "Gyakori minták: <span class=\"font-mono\">n-1</span>, <span class=\"font-mono\">n/2</span>, <span class=\"font-mono\">n-2</span>, <span class=\"font-mono\">utolsó számjegy eltávolítása</span>",
    "progress_warning" => "Nincs haladás = végtelen ciklus.",

    "step_by_step_thinking" => "Lépésről Lépésre Gondolkodási Folyamat",
    "step1" => "1. lépés",
    "step1_text" => "Azonosítsd a probléma legegyszerűbb változatát (alapeset)",
    "step2" => "2. lépés",
    "step2_text" => "Kérdezd meg: „Hogyan csökkenthetem a problémát egy lépéssel?”",
    "step3" => "3. lépés",
    "step3_text" => "Írd meg a rekurzív hívást, feltételezve, hogy a kisebb probléma már meg van oldva",
    "step4" => "4. lépés",
    "step4_text" => "Kombináld a kisebb probléma eredményét az aktuális lépéssel",
    "step5" => "5. lépés",
    "step5_text" => "Először tesztelj kis számokkal (1, 2, 3)",

    "return_types_label" => "MÉLYEBB MERÜLÉS",
    "return_types_title" => "Visszatérési Típusok a Rekurzióban",
    "return_types_desc" => "A rekurzív függvények vagy visszaadnak egy értéket, vagy csak mellékhatásokat hajtanak végre anélkül, hogy bármit visszaadnának.",

    "returning_value_title" => "Érték Visszaadása",
    "returning_value_desc" => "A legtöbb klasszikus rekurzív függvény visszaad egy értéket, amelyet a számításban használnak. Az eredmény a hívások visszatekerése során épül fel.",
    "returning_value_note" => "Ez a leggyakoribb minta — a válasz a visszaút során épül fel.",

    "void_recursion_title" => "Void Rekurzió (Nincs Visszatérés)",
    "void_recursion_desc" => "Néha a rekurziót csak mellékhatásokra használják (például kiírás vagy adatok módosítása). Ebben az esetben a függvény nem ad vissza semmit.",
    "void_recursion_note" => "A rekurzió továbbra is megtörténik, de nem használjuk a visszatérési értéket.",

    "recursion_types_label" => "REKURZIÓ TÍPUSAI",
    "recursion_types_title" => "Lineáris vs Fa Rekurzió",

    "linear_recursion_title" => "Lineáris Rekurzió",
    "linear_recursion_desc" => "A függvény csak EGY rekurzív hívást hajt végre. A hívási lánc egyenes (lineáris).",
    "linear_recursion_examples" => "Példák: faktoriális, számjegyek összege, hatványfüggvény, számok kiírása",

    "tree_recursion_title" => "Fa Rekurzió",
    "tree_recursion_desc" => "A függvény TÖBB rekurzív hívást hajt végre (általában 2 vagy többet). Hívási fát hoz létre.",
    "tree_recursion_examples" => "Példák: Fibonacci, összes részhalmaz generálása, néhány fa bejárás",

    "tree_recursion_warning_title" => "⚠️ Figyelem a Fa Rekurzióra",
    "tree_recursion_warning_desc" => "A fa rekurzió nagyon lassú lehet! A Fibonacci(40) több mint 100 millió hívást hajt végre. Használj memoizációt vagy alakítsd át iterációra, ha lehetséges.",

    "internal_mechanics" => "BELSŐ MŰKÖDÉS",
    "call_stack_explained" => "A Hívási Verem Magyarázata",
    "watch_animation" => "Animáció Megtekintése",
    "call_stack_description" => "Minden alkalommal, amikor egy függvény önmagát hívja, a számítógép létrehoz egy új keretet a veremben, amely tartalmazza:",
    "call_stack_item_1" => "függvény paramétereket",
    "call_stack_item_2" => "lokális változókat",
    "call_stack_item_3" => "visszatérési címet (hová menjen a hívás befejezése után)",
    "stack_limit_warning" => "<strong>Fontos:</strong> A verem mérete korlátozott. Túl sok rekurzív hívás = <span class=\"text-red-400\">Stack Overflow</span>.",
    "live_call_stack" => "ÉLŐ HIVÁSI VEREM",
    "push_call" => "HIVÁS PUSH",
    "pop_return" => "VISSZATÉRÉS POP",
    "reset" => "Visszaállítás",

    "classic_examples" => "Klasszikus Példák",
    "click_tabs_to_explore" => "Kattints a fülekre a felfedezéshez",
    "factorial_tab" => "Faktoriális",
    "factorial_desc" => "Klasszikus példa. n! = n × (n-1) × ... × 1. A leghíresebb rekurzív függvény.",
    "fibonacci_tab" => "Fibonacci",
    "fibonacci_desc" => "Fa rekurzió — kétszer hívja meg magát. Nagyon fontos megérteni az exponenciális növekedést.",
    "sum_digits_tab" => "Számjegyek Összege",
    "sum_digits_desc" => "Csökkenti a probléma méretét egy számjegy eltávolításával. Kiváló példa a lineáris rekurzióra.",
    "power_tab" => "Hatványozás",
    "power_desc" => "Exponenciális növekedés példája. Egyszerű, de erős rekurzív minta.",
    "code_with_comments" => "KÓD (megjegyzésekkel)",
    "copy_button" => "Másolás",
    "copied" => "Másolva",
    "try_it_yourself" => "Próbáld ki magad",
    "run_button" => "FUTTATÁS",
    "result_appears_here" => "Az eredmény itt jelenik meg...",

    "test_your_understanding" => "Teszteld a Tudásodat",
    "five_questions" => "5 kérdés a rekurzív függvényekről",
    "submit_answers" => "Válaszok Elküldése",
    "try_again" => "Próbáld Újra",

    "quiz_q1" => "Mi a legfontosabb része egy rekurzív függvénynek, ami megakadályozza a végtelen ciklusokat?",
    "quiz_q1_opt1" => "Az alapeset",
    "quiz_q1_opt2" => "A rekurzív hívás",
    "quiz_q1_opt3" => "A visszatérési típus",
    "quiz_q1_opt4" => "A függvény neve",

    "quiz_q2" => "Mi történik, ha egy rekurzív függvény soha nem éri el a leállási feltételét?",
    "quiz_q2_opt1" => "0-t ad vissza",
    "quiz_q2_opt2" => "Gyorsabban fut",
    "quiz_q2_opt3" => "Stack overflow-t okoz",
    "quiz_q2_opt4" => "Nem történik semmi",

    "quiz_q3" => "Miért kell minden rekurzív hívásnak haladnia az alapeset felé?",
    "quiz_q3_opt1" => "Memória megtakarításáért",
    "quiz_q3_opt2" => "A függvény gyorsabbá tételéért",
    "quiz_q3_opt3" => "Hogy végül elérje a leállási feltételt",
    "quiz_q3_opt4" => "Kevesebb CPU használatáért",

    "quiz_q4" => "Mit tartalmaz egy veremkeret?",
    "quiz_q4_opt1" => "Csak a visszatérési értéket",
    "quiz_q4_opt2" => "Paramétereket, lokális változókat és visszatérési címet",
    "quiz_q4_opt3" => "Csak a függvény nevét",
    "quiz_q4_opt4" => "Semmi fontosat",

    "quiz_q5" => "Melyik példa a fa-rekurzióra?",
    "quiz_q5_opt1" => "Faktoriális",
    "quiz_q5_opt2" => "Számjegyek összege",
    "quiz_q5_opt3" => "Fibonacci",
    "quiz_q5_opt4" => "Hatványfüggvény",

    "quiz_excellent" => "Kiváló! Valóban érted a rekurzív függvényeket.",
    "quiz_great" => "Nagyszerű munka! Elkezdted megérteni az alapfogalmakat.",
    "quiz_keep_practicing" => "Gyakorolj tovább — a rekurzió természetes lesz az ismétléssel."
];