<?php
return [
    // ── Navbar ──────────────────────────────────────────
    'share_animation' => 'Distribuie animația',
    'hide_timeline' => 'Ascunde Timeline',
    'shrink_timeline' => 'Micșorează Timeline',
    'hide_code' => 'Ascunde Codul',
    'go_to_editor' => 'Editor',
    'hide_compile' => 'Ascunde erorile',
    'show_compile' => 'Afiseaza erorile',
    'hide_output' => 'Ascunde ieșirea',
    'show_output' => 'Arată ieșirea',

    // ── Drag box / code panel ───────────────────────────
    'your_code' => 'Codul tău',
    'placeholder_code' => 'Introdu codul',
    'placeholder_vars' => 'Introdu variabilele suplimentare',
    'placeholder_call' => 'Introdu valorile',
    'execute' => 'Execută',
    'compile_error' => 'Eroare de compilare. Verifică codul tău și încearcă din nou.',

    // ── Share modal ─────────────────────────────────────
    'share_modal_title' => 'Distribuie Animația',
    'your_name' => 'Numele tău',
    'name_placeholder' => 'Introdu numele tău',
    'anim_title' => 'Titlul animației',
    'title_placeholder' => 'Dă un titlu animației',
    'cancel' => 'Anulează',
    'continue' => 'Continuă',

    // ── Share status popup ───────────────────────────────
    'shared_ok' => 'Animație distribuită cu succes.',
    'share_err_fields' => 'Te rog introdu numele și titlul animației.',
    'share_err_no_data' => 'Nu există date de animație în această sesiune. Rulează o animație mai întâi.',
    'share_err_folder' => 'Nu s-a putut crea folderul de distribuire.',
    'share_label_title' => 'Titlu:',
    'share_label_by' => 'De:',
    'copy_link' => 'Copiază linkul',
    'copied' => 'Copiat',
    'copy_failed' => 'Copiere eșuată',
    'close' => 'Închide',

    // ── Share meta panel (shared view) ──────────────────
    'meta_author' => 'Autor',
    'meta_title' => 'Titlu',
    'meta_created' => 'Data creării',

    // ── Captcha / execute feedback ───────────────────────
    'captcha_fail' => 'Te rog completează verificarea captcha înainte de execuție.',

    // ── Algorithms dropdown ──────────────────────────────
    'algo_custom' => 'Codul tău',
    'algo_fibonacci' => 'Fibonacci',
    'algo_factorial' => 'Factorial',
    'algo_knapsack' => 'Rucsac 0-1',
    'algo_coin_change' => 'Schimb de Monede',
    'algo_sum_digits' => 'Suma Cifrelor',
    'algo_binary_search' => 'Căutarea Binara',
    'algo_power' => 'Funcția de Putere',
    'algo_palindrome' => 'Palindrom',

    "back_button" => "⬅ Înapoi la Vizualizator",

    "recursion_title" => "Recursivitate",
    "what_is_recursion" => "Ce este recursivitatea",
    "recursion_definition" => "Recursivitatea este o tehnică în care o funcție se apelează pe ea însăși.",
    "recursion_simple_think" => 'Gândește-te așa:',
    "recursion_simple_formula" => '"Rezolv n → rezolv n-1 → n-2 → ... până la caz simplu"',

    "how_recursion_works_title" => "Cum funcționează recursivitatea",
    "how_recursion_works_1" => "De fiecare dată când o funcție se apelează, se creează un nou nivel în stivă.",
    "call_stack_intro" => "Stiva de apeluri reține:",
    "call_stack_items_intro" => "Aceasta conține:",
    "call_stack_item_1" => "parametrii funcției",
    "call_stack_item_2" => "variabile locale",
    "call_stack_item_3" => "adresa de returnare",
    "stack_unwind" => "Când se ajunge la cazul de bază, stiva se desfășoară (unwind).",

    "fibonacci_title" => "Fibonacci — de ce recursivitatea poate fi lentă",
    "fibonacci_code_intro" => "Exemplu de cod:",
    "fibonacci_explanation" => "Algoritmul recalculază aceleași valori de mai multe ori.",
    "fibonacci_example" => "Ex: fibonacci(5) recalculază fibonacci(3) de mai multe ori.",

    "digits_title" => "Sumă cifre",
    "digits_intro" => "Se calculează suma cifrelor unui număr folosind recursivitate.",
    "digits_example" => "1234 → 1 + 2 + 3 + 4 = 10",

    "thinking_process" => "Proces de gândire",
    "digits_breakdown_intro" => "Împărțim numărul în ultima cifră și restul numărului.",
    "digits_formula" => "sum(n) = ultima_cifră + sum(restul)",

    "cpp_solution" => "Soluție C++",
    "step_by_step" => "Execuție pas cu pas",

    "step1" => "sumDigits(1234)",
    "step2" => "= 4 + sumDigits(123)",
    "step3" => "= 4 + 3 + sumDigits(12)",
    "step4" => "= 4 + 3 + 2 + sumDigits(1)",
    "step5" => "= 4 + 3 + 2 + 1 + sumDigits(0)",
    "step6" => "= 4 + 3 + 2 + 1 + 0",
    "result" => "= 10",

    "why_it_works" => "De ce funcționează",
    "why_it_works_text" => "Problema se reduce la dimensiuni mai mici până ajunge la cazul de bază.",

    "important_note" => "Detaliu important",
    "integer_division_note" => "Împărțirea este întreagă: 123 / 10 = 12",
    "filters"=> "Optiuni vizualizare",
    "ai_sidebar_subtitle" => "Învață despre recursivitate cu propriul tău cod.",
    "ai_response_label" => "Răspuns",
    "send"=> "Trimite",
    "copy"=> "Copiază",
    "clear"=> "Șterge",
    "your_name"=> "Numele tău",
    "anim_title"=> "Titlul animației",
    "learn_recursion"=> "Despre recursivitate",
    "execute"=> "Execută",
    "ai_sidebar_title"=> "Asistent AI",
    "legend_param"=> "Parametru funcție",
    "legend_connection"=> "Linie de conexiune",
    "legend_direction"=> "Direcție",
    "legend_value"=> "Valoare",
    "legend_final_number"=> "Număr final",
    "nodes"=> "Noduri",
    "levels"=> "Niveluri",
    "output"=> "Ieșire program",
    "back_button" => "Înapoi",
    "page_title" => "Recursio • Stăpânirea Algoritmilor Recursivi",
    "hero_title" => "Stăpânește<br><span class=\"gradient-text\">Gândirea Recursivă</span>",
    "hero_subtitle" => "Învață exact cum funcționează funcțiile recursive, de ce sunt puternice, și cum să le scrii cu încredere.",

    "core_concept" => "CONCEPT DE BAZĂ",
    "how_to_think_recursively" => "Cum să Gândești Recursiv",
    "how_to_think_recursively_desc" => "Fiecare funcție recursivă urmează aceeași rețetă cu 3 ingrediente. Stăpânește-le și poți rezolva aproape orice problemă recursivă.",

    "base_case_title" => "1. Cazul de Bază",
    "base_case_desc" => "Condiția de oprire. Fără ea, recursivitatea nu se termină niciodată.",
    "base_case_explanation" => "Aceasta este cea mai simplă versiune a problemei care poate fi rezolvată direct.",

    "recursive_case_title" => "2. Cazul Recursiv",
    "recursive_case_desc" => "Partea în care funcția se apelează pe sine cu o problemă mai mică.",
    "recursive_case_explanation" => "Aceasta împarte problema mare într-una mai mică, identică.",

    "progress_title" => "3. Progres",
    "progress_desc" => "Trebuie să te apropii de cazul de bază la fiecare apel.",
    "progress_patterns" => "Modele comune: <span class=\"font-mono\">n-1</span>, <span class=\"font-mono\">n/2</span>, <span class=\"font-mono\">n-2</span>, <span class=\"font-mono\">elimină ultima cifră</span>",
    "progress_warning" => "Fără progres = buclă infinită.",

    "step_by_step_thinking" => "Proces de Gândire Pas cu Pas",
    "step1" => "Pasul 1",
    "step1_text" => "Identifică cea mai simplă versiune a problemei (cazul de bază)",
    "step2" => "Pasul 2",
    "step2_text" => "Întreabă: „Cum pot reduce problema cu un pas?”",
    "step3" => "Pasul 3",
    "step3_text" => "Scrie apelul recursiv presupunând că problema mai mică este deja rezolvată",
    "step4" => "Pasul 4",
    "step4_text" => "Combină rezultatul problemei mai mici cu pasul curent",
    "step5" => "Pasul 5",
    "step5_text" => "Testează cu numere mici (1, 2, 3) mai întâi",

    "return_types_label" => "APROFUNDARE",
    "return_types_title" => "Tipuri de Return în Recursivitate",
    "return_types_desc" => "Funcțiile recursive pot returna o valoare sau pot efectua acțiuni fără a returna nimic.",

    "returning_value_title" => "Returnează o Valoare",
    "returning_value_desc" => "Majoritatea funcțiilor recursive clasice returnează o valoare care este folosită în calcul. Rezultatul se construiește pe măsură ce apelurile se încheie.",
    "returning_value_note" => "Acesta este cel mai comun model — răspunsul se construiește la revenire.",

    "void_recursion_title" => "Recursivitate Void (Fără Return)",
    "void_recursion_desc" => "Uneori recursivitatea este folosită doar pentru efecte secundare (cum ar fi afișarea sau modificarea datelor). În acest caz funcția nu returnează nimic.",
    "void_recursion_note" => "Recursivitatea are loc în continuare, dar nu folosim valoarea returnată.",

    "recursion_types_label" => "TIPURI DE RECURSIVITATE",
    "recursion_types_title" => "Recursivitate Liniară vs de Tip Arbore",

    "linear_recursion_title" => "Recursivitate Liniară",
    "linear_recursion_desc" => "Funcția face doar UN apel recursiv. Lanțul de apeluri este drept (liniar).",
    "linear_recursion_examples" => "Exemple: factorial, sumă de cifre, funcția putere, afișare numere",

    "tree_recursion_title" => "Recursivitate de Tip Arbore",
    "tree_recursion_desc" => "Funcția face MAI MULTE apeluri recursive (de obicei 2 sau mai multe). Creează un arbore de apeluri.",
    "tree_recursion_examples" => "Exemple: Fibonacci, generare toate submulțimile, unele traversări de arbori",

    "tree_recursion_warning_title" => "⚠️ Avertisment despre Recursivitatea de Tip Arbore",
    "tree_recursion_warning_desc" => "Recursivitatea de tip arbore poate fi foarte lentă! Fibonacci(40) face peste 100 de milioane de apeluri. Folosește memoizare sau convertește în iterație când este posibil.",

    "internal_mechanics" => "MECANICA INTERNĂ",
    "call_stack_explained" => "Stiva de Apeluri Explicată",
    "watch_animation" => "Urmărește Animația",
    "call_stack_description" => "De fiecare dată când o funcție se apelează pe sine, calculatorul creează un nou cadru în stivă care conține:",
    "call_stack_item_1" => "parametrii funcției",
    "call_stack_item_2" => "variabile locale",
    "call_stack_item_3" => "adresa de returnare (unde să meargă după ce apelul se termină)",
    "stack_limit_warning" => "<strong>Important:</strong> Stiva are dimensiune limitată. Prea multe apeluri recursive = <span class=\"text-red-400\">Stack Overflow</span>.",
    "live_call_stack" => "STIVA DE APELURI LIVE",
    "push_call" => "APEL PUSH",
    "pop_return" => "RETURN POP",
    "reset" => "Resetează",

    "classic_examples" => "Exemple Clasice",
    "click_tabs_to_explore" => "Click pe tab-uri pentru a explora",
    "factorial_tab" => "Factorial",
    "factorial_desc" => "Exemplu clasic. n! = n × (n-1) × ... × 1. Cea mai faimoasă funcție recursivă.",
    "fibonacci_tab" => "Fibonacci",
    "fibonacci_desc" => "Recursivitate de tip arbore — se apelează de două ori. Foarte important de înțeles creșterea exponențială.",
    "sum_digits_tab" => "Sumă Cifre",
    "sum_digits_desc" => "Reduce dimensiunea problemei eliminând o cifră. Excelent exemplu de recursivitate liniară.",
    "power_tab" => "Putere",
    "power_desc" => "Exemplu de creștere exponențială. Model recursiv simplu dar puternic.",
    "code_with_comments" => "COD (cu comentarii)",
    "copy_button" => "Copiază",
    "copied" => "Copiat",
    "try_it_yourself" => "Încearcă singur",
    "run_button" => "RUN",
    "result_appears_here" => "Rezultatul va apărea aici...",

    "test_your_understanding" => "Testează-ți Înțelegerea",
    "five_questions" => "5 întrebări despre funcții recursive",
    "submit_answers" => "Trimite Răspunsurile",
    "try_again" => "Încearcă din Nou",

    "quiz_q1" => "Care este cea mai importantă parte a unei funcții recursive care previne buclele infinite?",
    "quiz_q1_opt1" => "Cazul de bază",
    "quiz_q1_opt2" => "Apelul recursiv",
    "quiz_q1_opt3" => "Tipul de returnare",
    "quiz_q1_opt4" => "Numele funcției",

    "quiz_q2" => "Ce se întâmplă dacă o funcție recursivă nu ajunge niciodată la condiția de oprire?",
    "quiz_q2_opt1" => "Returnează 0",
    "quiz_q2_opt2" => "Rulează mai rapid",
    "quiz_q2_opt3" => "Cauzează stack overflow",
    "quiz_q2_opt4" => "Nu se întâmplă nimic",

    "quiz_q3" => "De ce trebuie ca fiecare apel recursiv să facă progres spre cazul de bază?",
    "quiz_q3_opt1" => "Pentru a economisi memorie",
    "quiz_q3_opt2" => "Pentru a face funcția mai rapidă",
    "quiz_q3_opt3" => "Pentru a ajunge eventual la condiția de oprire",
    "quiz_q3_opt4" => "Pentru a folosi mai puțin CPU",

    "quiz_q4" => "Ce conține un cadru din stivă?",
    "quiz_q4_opt1" => "Doar valoarea de returnare",
    "quiz_q4_opt2" => "Parametri, variabile locale și adresa de returnare",
    "quiz_q4_opt3" => "Doar numele funcției",
    "quiz_q4_opt4" => "Nimic important",

    "quiz_q5" => "Care este un exemplu de recursivitate de tip arbore?",
    "quiz_q5_opt1" => "Factorial",
    "quiz_q5_opt2" => "Sumă de cifre",
    "quiz_q5_opt3" => "Fibonacci",
    "quiz_q5_opt4" => "Funcția putere",

    "quiz_excellent" => "Excelent! Înțelegi cu adevărat funcțiile recursive.",
    "quiz_great" => "Foarte bine! Începi să înțelegi conceptele de bază.",
    "quiz_keep_practicing" => "Continuă să exersezi — recursivitatea devine naturală cu practică."
];
