<?php
return [
    // ── Navbar ──────────────────────────────────────────
    'share_animation' => 'Share animation',
    'hide_timeline' => 'Hide Timeline',
    'shrink_timeline' => 'Shrink Timeline',
    'hide_zoom' => 'Hide Zoom',
    'hide_code' => 'Hide Code',
    'go_to_editor' => 'Editor',
    'hide_compile' => 'Hide errors',
    'hide_output' => 'Hide output',

    // ── Drag box / code panel ───────────────────────────
    'your_code' => 'Your code',
    'placeholder_code' => 'Enter code',
    'placeholder_vars' => 'Enter supplementary variables',
    'placeholder_call' => 'Enter the function call',
    'execute' => 'Execute',
    'compile_error' => 'Compilation error. Check your code and try again.',

    // ── Share modal ─────────────────────────────────────
    'share_modal_title' => 'Share Animation',
    'your_name' => 'Your name',
    'name_placeholder' => 'Enter your name',
    'anim_title' => 'Animation title',
    'title_placeholder' => 'Give your animation a title',
    'cancel' => 'Cancel',
    'continue' => 'Continue',

    // ── Share status popup ───────────────────────────────
    'shared_ok' => 'Animation shared successfully.',
    'share_err_fields' => 'Please enter your name and an animation title.',
    'share_err_no_data' => 'No animation data found in this session. Run an animation first.',
    'share_err_folder' => 'Could not create share folder.',
    'share_label_title' => 'Title:',
    'share_label_by' => 'By:',
    'copy_link' => 'Copy link',
    'copied' => 'Copied',
    'copy_failed' => 'Copy failed',
    'close' => 'Close',

    // ── Share meta panel (shared view) ──────────────────
    'share_err_no_exec' => 'You have not executed the code or it has compilation errors!',
    'share_err_compile' => 'Your code has compilation errors. Fix them before sharing!',
    'meta_author' => 'Author',
    'meta_title' => 'Title',
    'meta_created' => 'Creation date',

    // ── Captcha / execute feedback ───────────────────────
    'captcha_fail' => 'Please complete the captcha verification before executing.',

    // ── Algorithms dropdown ──────────────────────────────
    'algo_custom' => 'Your code',
    'algo_fibonacci' => 'Fibonacci',
    'algo_factorial' => 'Factorial',
    'algo_knapsack' => '0-1 Knapsack',
    'algo_coin_change' => 'Coin Change',
    'algo_sum_digits' => 'Sum of Digits',
    'algo_binary_search' => 'Binary Search',
    'algo_power' => 'Power Function',
    'algo_palindrome' => 'Palindrome',

    "back_button" => "⬅ Back to Visualizer",

    "what_is_recursion" => "What is recursion",
    "recursion_definition" => "Recursion is a technique where a function calls itself.",
    "recursion_simple_think" => "Think of it like:",
    "recursion_simple_formula" => "\"Solve n → solve n-1 → n-2 → ... until a simple case\"",

    "how_recursion_works_title" => "How recursion works",
    "how_recursion_works_1" => "Each time a function calls itself, a new layer is added to the stack.",
    "call_stack_intro" => "The call stack stores:",
    "call_stack_items_intro" => "It contains:",
    "call_stack_item_1" => "function parameters",
    "call_stack_item_2" => "local variables",
    "call_stack_item_3" => "return address",
    "stack_unwind" => "When the base case is reached, the stack starts to unwind.",

    "fibonacci_title" => "Fibonacci — why recursion can be slow",
    "fibonacci_code_intro" => "Code example:",
    "fibonacci_explanation" => "The algorithm recalculates the same values multiple times.",
    "fibonacci_example" => "Example: fibonacci(5) recalculates fibonacci(3) multiple times.",

    "digits_title" => "Sum of digits",
    "digits_intro" => "We compute the sum of digits using recursion.",
    "digits_example" => "1234 → 1 + 2 + 3 + 4 = 10",

    "thinking_process" => "Thinking process",
    "digits_breakdown_intro" => "We split the number into last digit and the remaining number.",
    "digits_formula" => "sum(n) = last_digit + sum(remaining)",

    "cpp_solution" => "C++ Solution",
    "step_by_step" => "Step-by-step execution",

    "step1" => "sumDigits(1234)",
    "step2" => "= 4 + sumDigits(123)",
    "step3" => "= 4 + 3 + sumDigits(12)",
    "step4" => "= 4 + 3 + 2 + sumDigits(1)",
    "step5" => "= 4 + 3 + 2 + 1 + sumDigits(0)",
    "step6" => "= 4 + 3 + 2 + 1 + 0",
    "result" => "= 10",

    "why_it_works" => "Why it works",
    "why_it_works_text" => "The problem is reduced step by step until the base case is reached.",

    "important_note" => "Important detail",
    "integer_division_note" => "Integer division: 123 / 10 = 12",
    "filters" => "View options",
    "ai_sidebar_subtitle" => "Learn about recursion with your own code.",
    "ai_response_label" => "Response",
    "send" => "Send",
    "copy" => "Copy",
    "clear" => "Clear",
    "your_name" => "Your name",
    "anim_title" => "Animation title",
    "learn_recursion" => "About Recursio",
    "execute" => "Execute",
    "ai_sidebar_title" => "AI Assistant",
    "legend_param" => "Function parameter",
    "legend_connection" => "Connection line",
    "legend_direction" => "Direction",
    "legend_value" => "Value",
    "legend_final_number" => "Final number",
    "nodes" => "Nodes",
    "levels" => "Levels",
    "output" => "Program output",
    "back_button" => "Back",
    "page_title" => "Recursio • Mastering Recursive Algorithms",
    "hero_title" => "Master<br><span class=\"gradient-text\">Recursive Thinking</span>",
    "hero_subtitle" => "Learn exactly how recursive functions work, why they are powerful, and how to write them with confidence.",

    "core_concept" => "CORE CONCEPT",
    "how_to_think_recursively" => "How to Think Recursively",
    "how_to_think_recursively_desc" => "Every recursive function follows the same 3-ingredient recipe. Master these and you can solve almost any recursive problem.",

    "base_case_title" => "1. Base Case",
    "base_case_desc" => "The <strong>stopping condition</strong>. Without it, recursion never ends.",
    "base_case_explanation" => "This is the simplest version of the problem that can be solved directly.",

    "recursive_case_title" => "2. Recursive Case",
    "recursive_case_desc" => "The part where the function <strong>calls itself</strong> with a smaller problem.",
    "recursive_case_explanation" => "This breaks the big problem into a smaller identical one.",

    "progress_title" => "3. Progress",
    "progress_desc" => "You must <strong>get closer</strong> to the base case with every call.",
    "progress_patterns" => "Common patterns: <span class=\"font-mono\">n-1</span>, <span class=\"font-mono\">n/2</span>, <span class=\"font-mono\">n-2</span>, <span class=\"font-mono\">remove last digit</span>",
    "progress_warning" => "No progress = infinite loop.",

    "step_by_step_thinking" => "Step-by-Step Thinking Process",
    "step1" => "Step 1",
    "step1_text" => "Identify the <strong>simplest</strong> version of the problem (base case)",
    "step2" => "Step 2",
    "step2_text" => "Ask: “How can I reduce the problem by one step?”",
    "step3" => "Step 3",
    "step3_text" => "Write the recursive call assuming the smaller problem is already solved",
    "step4" => "Step 4",
    "step4_text" => "Combine the result of the smaller problem with the current step",
    "step5" => "Step 5",
    "step5_text" => "Test with small numbers (1, 2, 3) first",

    "return_types_label" => "DEEP DIVE",
    "return_types_title" => "Return Types in Recursion",
    "return_types_desc" => "Recursive functions can either return a value or perform actions without returning anything.",

    "returning_value_title" => "Returning a Value",
    "returning_value_desc" => "Most classic recursive functions return a value that is used in the calculation. The result is built up as the calls unwind.",
    "returning_value_note" => "This is the most common pattern — the answer is constructed on the way back.",

    "void_recursion_title" => "Void Recursion (No Return)",
    "void_recursion_desc" => "Sometimes recursion is used only for side effects (like printing or modifying data). In this case the function returns nothing.",
    "void_recursion_note" => "The recursion still happens, but we don't use the return value.",

    "recursion_types_label" => "TYPES OF RECURSION",
    "recursion_types_title" => "Linear vs Tree Recursion",

    "linear_recursion_title" => "Linear Recursion",
    "linear_recursion_desc" => "The function makes only ONE recursive call. The call chain is straight (linear).",
    "linear_recursion_examples" => "Examples: factorial, sum of digits, power function, printing numbers",

    "tree_recursion_title" => "Tree Recursion",
    "tree_recursion_desc" => "The function makes MULTIPLE recursive calls (usually 2 or more). It creates a tree of calls.",
    "tree_recursion_examples" => "Examples: Fibonacci, generating all subsets, some tree traversals",

    "tree_recursion_warning_title" => "⚠️ Warning about Tree Recursion",
    "tree_recursion_warning_desc" => "Tree recursion can be very slow! Fibonacci(40) makes over 100 million calls. Use memoization or convert to iteration when possible.",

    "internal_mechanics" => "INTERNAL MECHANICS",
    "call_stack_explained" => "The Call Stack Explained",
    "watch_animation" => "Watch Animation",
    "call_stack_description" => "Every time a function calls itself, the computer creates a new <strong>stack frame</strong> containing:",
    "call_stack_item_1" => "function parameters",
    "call_stack_item_2" => "local variables",
    "call_stack_item_3" => "return address (where to go after this call finishes)",
    "stack_limit_warning" => "<strong>Important:</strong> The stack has limited size. Too many recursive calls = <span class=\"text-red-400\">Stack Overflow</span>.",
    "live_call_stack" => "LIVE CALL STACK",
    "push_call" => "PUSH CALL",
    "pop_return" => "POP RETURN",
    "reset" => "Reset",

    "classic_examples" => "Classic Examples",
    "click_tabs_to_explore" => "Click tabs to explore",
    "factorial_tab" => "Factorial",
    "factorial_desc" => "Classic example. n! = n × (n-1) × ... × 1. The most famous recursive function.",
    "fibonacci_tab" => "Fibonacci",
    "fibonacci_desc" => "Tree recursion — calls itself twice. Very important to understand exponential growth.",
    "sum_digits_tab" => "Sum of Digits",
    "sum_digits_desc" => "Reduces problem size by removing one digit. Great example of linear recursion.",
    "power_tab" => "Power",
    "power_desc" => "Exponential growth example. Simple but powerful recursive pattern.",
    "code_with_comments" => "CODE (with comments)",
    "copy_button" => "Copy",
    "copied" => "Copied",
    "try_it_yourself" => "Try it yourself",
    "run_button" => "RUN",
    "result_appears_here" => "Result will appear here...",

    "test_your_understanding" => "Test Your Understanding",
    "five_questions" => "5 questions about recursive functions",
    "submit_answers" => "Submit Answers",
    "try_again" => "Try Again",

    "quiz_q1" => "What is the most important part of a recursive function that prevents infinite loops?",
    "quiz_q1_opt1" => "The base case",
    "quiz_q1_opt2" => "The recursive call",
    "quiz_q1_opt3" => "The return type",
    "quiz_q1_opt4" => "The function name",

    "quiz_q2" => "What happens if a recursive function never reaches its stopping condition?",
    "quiz_q2_opt1" => "It returns 0",
    "quiz_q2_opt2" => "It runs faster",
    "quiz_q2_opt3" => "It causes stack overflow",
    "quiz_q2_opt4" => "Nothing happens",

    "quiz_q3" => "Why must each recursive call make progress toward the base case?",
    "quiz_q3_opt1" => "To save memory",
    "quiz_q3_opt2" => "To make the function faster",
    "quiz_q3_opt3" => "To eventually reach the stopping condition",
    "quiz_q3_opt4" => "To use less CPU",

    "quiz_q4" => "What does a stack frame contain?",
    "quiz_q4_opt1" => "Only the return value",
    "quiz_q4_opt2" => "Parameters, local variables, and return address",
    "quiz_q4_opt3" => "Only the function name",
    "quiz_q4_opt4" => "Nothing important",

    "quiz_q5" => "Which is an example of tree recursion?",
    "quiz_q5_opt1" => "Factorial",
    "quiz_q5_opt2" => "Sum of digits",
    "quiz_q5_opt3" => "Fibonacci",
    "quiz_q5_opt4" => "Power function",

    "quiz_excellent" => "Excellent! You truly understand recursive functions.",
    "quiz_great" => "Great job! You are getting the core concepts.",
    "quiz_keep_practicing" => "Keep practicing — recursion becomes natural with repetition.",
    "executing_code" => "Executing code",
    "generating_matrix" => "Generating matrix",
    "analyzing_recursion" => "Analyzing recursion",
    "calling_ai_assistant" => "Calling AI assistant",
    "building_visualization" => "Building visualization",
    'hint_code' => 'In this field, enter the code of your recursive function.',
    'hint_supvars' => 'Note: supplementary variables are for data that cannot be declared inside the function (e.g. arrays, matrices).',
    'hint_call' => 'Enter your function call, e.g: factorial(5)',
    'rotate_device' => 'Please rotate your device to portrait mode for a better experience.',
    'rotate_warn' => 'You rotated your device. The animation was built for the previous orientation, so it may look misaligned now. Regenerate it for the current one.',
    'rotate_regenerate' => 'Regenerate',
    'rotate_dismiss' => 'Keep as is',

    "disclaimer" => "Currently, only the iostream library is available. Standard output is handled via cout.",
	
	'title' => 'Recursio — Overview',
        'hero_h' => 'Recursion comes to life',
        'hero_p' => 'Recursio turns a recursive function into an animated tree: every call becomes a node, and you watch the tree build up and the results come back — step by step.',
        'what_e' => 'In short',
        'what_h' => 'What is recursion?',
        'what_p' => 'A recursive function solves a problem by calling itself on a smaller version of it, until it reaches a simple case it knows directly. It needs exactly two things:',
        'base_h' => 'The base case',
        'base_p' => 'The stopping condition — the simplest situation, where the answer is known at once. Without it, recursion never ends.',
        'rec_h' => 'The recursive case',
        'rec_p' => 'The function calling itself, but on a slightly smaller problem. Every step must move closer to the base case.',
        'cmt_base' => '// base case',
        'cmt_rec' => '// recursive case',
        'viz_e' => 'Visual guide',
        'viz_h' => 'What the visualizer elements mean',
        'viz_p' => 'When you run a function, Recursio draws the call tree. Here is what each element means:',
        'fig_cap' => 'Example: the tree for fibonacci(6)',
        'ph1' => 'The annotated tree image will go here',
        'ph2' => '(I will add it when you send the screenshot from the visualizer)',
        'leg1_h' => 'Function parameter',
        'leg1_p' => 'Each circle is a function call. The number inside is the parameter value it was called with.',
        'leg2_h' => 'Connection line',
        'leg2_p' => 'Links a call to the sub-calls it triggers, forming the branches of the tree.',
        'leg3_h' => 'Direction',
        'leg3_p' => 'Shows the way recursion moves, from the initial call down to the base case.',
        'leg4_h' => 'Returned value',
        'leg4_p' => 'The colored number shows what a call returns once it has finished.',
        'leg5_h' => 'Final returned value',
        'leg5_p' => 'The result returned by the root call — the final answer of the recursion.',
        'ai_e' => 'AI assistant',
        'ai_h' => 'Learn with an AI assistant by your side',
        'ai_p' => 'Recursio has a built-in AI assistant, like a tutor always within reach. It does not just hand you the answer — it helps you understand what is happening behind the recursion.',
        'ai1_h' => 'Explains your own code',
        'ai1_p' => 'When you run a function, Recursio asks the AI to describe what your code does, in plain language — no digging through docs.',
        'ai2_h' => 'Answers your questions',
        'ai2_p' => 'Open the assistant in the sidebar and ask anything about your code or recursion. It remembers the conversation, so you can keep asking follow-ups.',
        'ai3_h' => 'Helps you understand and debug',
        'ai3_p' => 'Ask the AI to trace the calls step by step and point out where things go wrong.',
        'ai_tip_h' => 'Questions you could ask:',
        'ai_q1' => 'Why does my function cause a stack overflow?',
        'ai_q2' => 'Walk me through what fibonacci(5) does, step by step.',
        'ai_q3' => 'What is the base case here and why is it needed?',
        'cta_h' => 'Ready to try it?',
        'cta_p' => 'Write your own recursive function and watch the tree build up in real time.',
        'cta_btn' => 'Open the visualizer'
];
